- type: playTimeTracker
  id: Jobsmuggler

- type: playTimeTracker
  id: JobMedSyn

- type: playTimeTracker
  id: JobStormtrooper

- type: playTimeTracker
  id: JobCommander

- type: playTimeTracker
  id: JobparaMedical
