- type: startingGear
  id: SyndicateReinforcementSpySmugger
  parent: SyndicateOperativeClothing
  equipment:
    id: SyndiPDACadet
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    head: ClothingHeadHatRedsoft
    pocket1: WeaponPistolViper
  storage:
    back:
    - ToolboxKadet
